### PR TITLE
Fix #2: Print more information on failed requests

### LINKED ISSUE #2: More info for error "Failed to get a response. Have you set the OPENAI_API_KEY variable?"
Hi, looking forward to trying this, getting an error though and I'm not sure how to debug it. 

The key is freshly made from https://beta.openai.com/account/api-keys. 
I'm using fish shell 3.5.1 in MacOS.

```
 ❯ echo $OPENAI_API_KEY
sk-<key hidden>
 ❯ plz "list files"
✖ Failed to get a response. Have you set the OPENAI_API_KEY variable?
```

I've yet to try to code in Rust so I'm not set up to try to modify the source and see what's happening.

### PR DESCRIPTION
**Pull request by soerface**
Discriminate between server and client errors. If it's a client error, parse the JSON to pretty print the failure reason. I assume that every client error response looks similar (contains `error.message`).

This is the response I got because a payment method was missing:

```bash
$ curl -X POST https://api.openai.com/v1/completions \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "top_p": 1,
    "stop": "```",
    "temperature": 0,
    "suffix": "\n```",
    "max_tokens": 1000,
    "presence_penalty": 0,
    "frequency_penalty": 0,
    "model": "text-davinci-003",
    "prompt": "your prompt"                
}'

{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

Fixes #2

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -53,17 +53,26 @@ fn main() {
...
-                "Failed to get a response. Have you set the OPENAI_API_KEY variable?"
-                    .red()
-                    .to_string(),
-            );
-            std::process::exit(1);
-        });
+        .unwrap();
+
+    let status_code = response.status();
+    if status_code.is_client_error() {
```
Comment (soerface) [inline src/main.rs:51]: I wasn't able to get the response body after using `error_for_status`. It looks to me like the `Error` type does not expose the response body. Since `error_for_status` is not doing much more than turning the response into ok / error by using `if status.is_client_error() || status.is_server_error() {`, I just use those methods here directly.
